using Diwali.Domain;
using Diwali.Application;
using Microsoft.EntityFrameworkCore;
namespace Diwali.Infrastructure;
public class PosDb(DbContextOptions<PosDb> options):DbContext(options),IPosDb {
 public DbSet<Product> Products=>Set<Product>(); public DbSet<Category> Categories=>Set<Category>(); public DbSet<Bill> Bills=>Set<Bill>(); public DbSet<BillItem> BillItems=>Set<BillItem>(); public DbSet<User> Users=>Set<User>(); public DbSet<InventoryTransaction> InventoryTransactions=>Set<InventoryTransaction>(); public DbSet<ShopSettings> Settings=>Set<ShopSettings>();
 protected override void OnModelCreating(ModelBuilder m)=>Configure(m);
 public static void Configure(ModelBuilder m) {
  m.HasAnnotation("Relational:MaxIdentifierLength",63);
  m.UseIdentityByDefaultColumns();
  m.Entity<Product>().ToTable("Products"); m.Entity<Product>().HasKey(x=>x.Id);
  m.Entity<Product>().Property(x=>x.Id).ValueGeneratedNever();
  m.Entity<Product>().Property(x=>x.SerialNumber).IsRequired();
  m.Entity<Product>().Property(x=>x.Name).IsRequired();
  m.Entity<Product>().Property(x=>x.CategoryId);
  m.Entity<Product>().Property(x=>x.Price);
  m.Entity<Product>().Property(x=>x.MRP);
  m.Entity<Product>().Property(x=>x.StockQuantity);
  m.Entity<Product>().Property(x=>x.IsActive);
  m.Entity<Product>().Property(x=>x.CreatedAt);
  m.Entity<Product>().Property(x=>x.UpdatedAt);
  m.Entity<Product>().Property(x=>x.Version);
  m.Entity<Category>().ToTable("Categories"); m.Entity<Category>().HasKey(x=>x.Id);
  m.Entity<Category>().Property(x=>x.Id).ValueGeneratedNever();
  m.Entity<Category>().Property(x=>x.Name).IsRequired();
  m.Entity<Category>().Property(x=>x.IsActive);
  m.Entity<Category>().Property(x=>x.CreatedAt);
  m.Entity<User>().ToTable("Users"); m.Entity<User>().HasKey(x=>x.Id);
  m.Entity<User>().Property(x=>x.Id).ValueGeneratedNever();
  m.Entity<User>().Property(x=>x.Name).IsRequired();
  m.Entity<User>().Property(x=>x.Username).IsRequired();
  m.Entity<User>().Property(x=>x.PasswordHash).IsRequired();
  m.Entity<User>().Property(x=>x.Role).IsRequired();
  m.Entity<User>().Property(x=>x.IsActive);
  m.Entity<User>().Property(x=>x.SessionVersion);
  m.Entity<User>().Property(x=>x.CreatedAt);
  m.Entity<Bill>().ToTable("Bills"); m.Entity<Bill>().HasKey(x=>x.Id);
  m.Entity<Bill>().Property(x=>x.Id).ValueGeneratedNever();
  m.Entity<Bill>().Property(x=>x.BillNumber).IsRequired();
  m.Entity<Bill>().Property(x=>x.BillDate);
  m.Entity<Bill>().Property(x=>x.Subtotal);
  m.Entity<Bill>().Property(x=>x.DiscountPercentage);
  m.Entity<Bill>().Property(x=>x.DiscountAmount);
  m.Entity<Bill>().Property(x=>x.FinalAmount);
  m.Entity<Bill>().Property(x=>x.CreatedBy);
  m.Entity<Bill>().Property(x=>x.CreatedAt);
  m.Entity<Bill>().Property(x=>x.SubmissionId);
  m.Entity<Bill>().Property(x=>x.RequestHash).IsRequired();
  m.Entity<Bill>().Property(x=>x.ShopName).IsRequired();
  m.Entity<Bill>().Property(x=>x.ShopAddress).IsRequired();
  m.Entity<Bill>().Property(x=>x.ShopPhone).IsRequired();
  m.Entity<BillItem>().ToTable("BillItems"); m.Entity<BillItem>().HasKey(x=>x.Id);
  m.Entity<BillItem>().Property(x=>x.Id).ValueGeneratedNever();
  m.Entity<BillItem>().Property(x=>x.BillId);
  m.Entity<BillItem>().Property(x=>x.ProductId);
  m.Entity<BillItem>().Property(x=>x.SerialNumber).IsRequired();
  m.Entity<BillItem>().Property(x=>x.ProductName).IsRequired();
  m.Entity<BillItem>().Property(x=>x.PriceAtSale);
  m.Entity<BillItem>().Property(x=>x.Quantity);
  m.Entity<BillItem>().Property(x=>x.Total);
  m.Entity<InventoryTransaction>().ToTable("InventoryTransactions"); m.Entity<InventoryTransaction>().HasKey(x=>x.Id);
  m.Entity<InventoryTransaction>().Property(x=>x.Id).ValueGeneratedNever();
  m.Entity<InventoryTransaction>().Property(x=>x.ProductId);
  m.Entity<InventoryTransaction>().Property(x=>x.TransactionType).IsRequired();
  m.Entity<InventoryTransaction>().Property(x=>x.Quantity);
  m.Entity<InventoryTransaction>().Property(x=>x.ReferenceBillId);
  m.Entity<InventoryTransaction>().Property(x=>x.PreviousStock);
  m.Entity<InventoryTransaction>().Property(x=>x.NewStock);
  m.Entity<InventoryTransaction>().Property(x=>x.CreatedBy);
  m.Entity<InventoryTransaction>().Property(x=>x.CreatedAt);
  m.Entity<InventoryTransaction>().Property(x=>x.Reason).IsRequired();
  m.Entity<ShopSettings>().ToTable("Settings"); m.Entity<ShopSettings>().HasKey(x=>x.Id);
  m.Entity<ShopSettings>().Property(x=>x.Id).ValueGeneratedNever();
  m.Entity<ShopSettings>().Property(x=>x.Name).IsRequired();
  m.Entity<ShopSettings>().Property(x=>x.Address).IsRequired();
  m.Entity<ShopSettings>().Property(x=>x.Phone).IsRequired();
  m.Entity<ShopSettings>().Property(x=>x.LowStockThreshold);
  m.Entity<Product>().ToTable("Products",t=>{t.HasCheckConstraint("CK_Product_Price","\"Price\" >= 0 AND \"MRP\" >= \"Price\"");t.HasCheckConstraint("CK_Product_Stock","\"StockQuantity\" >= 0");});
  m.Entity<Product>().HasIndex(p=>p.SerialNumber).IsUnique(); m.Entity<Product>().HasIndex(p=>p.CategoryId);
  m.Entity<Product>().Property(p=>p.Version).HasColumnName("xmin").HasColumnType("xid").IsRowVersion(); m.Entity<Product>().HasOne<Category>().WithMany().HasForeignKey(p=>p.CategoryId).OnDelete(DeleteBehavior.Restrict);
  m.Entity<Category>().HasIndex(c=>c.Name).IsUnique(); m.Entity<User>().HasIndex(u=>u.Username).IsUnique();
  m.Entity<Bill>().HasIndex(b=>b.BillNumber).IsUnique(); m.Entity<Bill>().HasIndex(b=>new{b.CreatedBy,b.SubmissionId}).IsUnique(); m.Entity<Bill>().HasIndex(b=>b.BillDate);
  m.Entity<Bill>().HasOne<User>().WithMany().HasForeignKey(b=>b.CreatedBy).OnDelete(DeleteBehavior.Restrict);
  m.Entity<Bill>().HasMany(b=>b.Items).WithOne().HasForeignKey(i=>i.BillId).OnDelete(DeleteBehavior.Restrict);
  m.Entity<BillItem>().HasOne<Product>().WithMany().HasForeignKey(i=>i.ProductId).OnDelete(DeleteBehavior.Restrict);
  m.Entity<InventoryTransaction>().HasOne<Product>().WithMany().HasForeignKey(i=>i.ProductId).OnDelete(DeleteBehavior.Restrict);
  m.Entity<InventoryTransaction>().HasOne<User>().WithMany().HasForeignKey(i=>i.CreatedBy).OnDelete(DeleteBehavior.Restrict);
  m.Entity<InventoryTransaction>().HasOne<Bill>().WithMany().HasForeignKey(i=>i.ReferenceBillId).OnDelete(DeleteBehavior.Restrict);
  m.Entity<InventoryTransaction>().HasIndex(i=>i.CreatedAt);
  m.Entity<BillItem>().HasIndex(x=>x.BillId);m.Entity<BillItem>().HasIndex(x=>x.ProductId);
  m.Entity<InventoryTransaction>().HasIndex(x=>x.ProductId);m.Entity<InventoryTransaction>().HasIndex(x=>x.CreatedBy);m.Entity<InventoryTransaction>().HasIndex(x=>x.ReferenceBillId);
  foreach(var e in m.Model.GetEntityTypes())foreach(var p in e.GetProperties()) {
   if(p.Name=="Version")continue;
   var type=Nullable.GetUnderlyingType(p.ClrType)??p.ClrType;
   p.SetColumnType(type==typeof(Guid)?"uuid":type==typeof(string)?"text":type==typeof(int)?"integer":type==typeof(bool)?"boolean":type==typeof(DateTime)?"timestamp with time zone":type==typeof(decimal)?"numeric(18,2)":null);
  }
  foreach(var e in m.Model.GetEntityTypes())foreach(var p in e.GetProperties())if(p.ClrType==typeof(decimal)){p.SetPrecision(18);p.SetScale(2);}
 }
}
