import React,{useEffect,useState} from 'react';import {createRoot} from 'react-dom/client';import {QueryClient,QueryClientProvider,useMutation,useQuery,useQueryClient} from '@tanstack/react-query';import {useForm} from 'react-hook-form';import {Sparkles,ShoppingBag,LayoutDashboard,Package,Tags,Boxes,ReceiptText,Users as UsersIcon,Settings as SettingsIcon,LogOut,Menu,X,ShieldCheck} from 'lucide-react';import {api,ApiError} from './api';import {User} from './types';import {POS} from './POS';import {Products,Categories,Inventory,Users,Shop} from './Admin';import {Dashboard,History} from './Reports';import {ErrorBox,Loading,Field} from './components';import './style.css';
const client=new QueryClient({defaultOptions:{queries:{retry:(count,error)=>!(error instanceof ApiError&&[401,403].includes(error.status))&&count<1,staleTime:15000,refetchOnWindowFocus:true}}});
function Login(){const q=useQueryClient();const {register,handleSubmit}=useForm<{username:string;password:string}>();const login=useMutation({mutationFn:(v:{username:string;password:string})=>api<User>('/auth/login','POST',v),onSuccess:u=>q.setQueryData(['me'],u)});return <main className="login-page"><div className="login-brand"><div className="brand-symbol"><Sparkles size={30}/></div><span>DIWALI<span>CRACKERS POS</span></span></div><section className="login-card"><span className="eyebrow">WELCOME BACK</span><h1>Ready for a bright day?</h1><p className="muted">Sign in to your shop’s billing counter.</p><form onSubmit={handleSubmit(v=>login.mutate(v))}><Field label="Username"><input autoFocus autoComplete="username" required {...register('username',{required:true})}/></Field><Field label="Password"><input type="password" autoComplete="current-password" required {...register('password',{required:true})}/></Field><ErrorBox error={login.error}/><button className="primary complete" disabled={login.isPending}>{login.isPending?'Signing in…':'Sign in'}</button></form><p className="login-note"><ShieldCheck size={16}/> Secure access for admins and cashiers</p></section><p className="login-footer">A brighter way to run your festive season.</p></main>}
function App(){const q=useQueryClient();const me=useQuery({queryKey:['me'],queryFn:()=>api<User>('/auth/me'),retry:false});const [route,setRoute]=useState('pos'),[nav,setNav]=useState(false),[error,setError]=useState<unknown>();useEffect(()=>{const expired=()=>{q.clear();q.setQueryData(['me'],null)};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[q]);
 if(me.isPending)return <Loading/>;if(!me.data){if(me.error instanceof ApiError&&me.error.status!==401)return <div className="connection-error"><h1>Shop server unavailable</h1><ErrorBox error={me.error}/><button onClick={()=>me.refetch()}>Try again</button><p>Start the ASP.NET Core API and PostgreSQL database to sign in.</p></div>;return <Login/>}
 const user=me.data,admin=user.role==='Admin';const links=[{id:'pos',label:'New bill',icon:ShoppingBag},{id:'dashboard',label:'Dashboard',icon:LayoutDashboard,admin:true},{id:'products',label:'Products',icon:Package,admin:true},{id:'categories',label:'Categories',icon:Tags,admin:true},{id:'inventory',label:'Inventory',icon:Boxes,admin:true},{id:'history',label:'Bill history',icon:ReceiptText},{id:'users',label:'Users',icon:UsersIcon,admin:true},{id:'settings',label:'Shop settings',icon:SettingsIcon,admin:true}];
 function navigate(id:string){if(route==='pos'&&id!==route&&!confirm('Leave New bill? Any unsaved cart will be cleared.'))return;setRoute(id);setNav(false)}
 async function logout(){if(!confirm('Sign out? Any unsaved bill will be cleared.'))return;try{await api('/auth/logout','POST');q.clear();q.setQueryData(['me'],null);setRoute('pos')}catch(e){setError(e)}}
 const content=route==='pos'?<POS/>:route==='history'?<History/>:!admin?<POS/>:route==='dashboard'?<Dashboard/>:route==='products'?<Products/>:route==='categories'?<Categories/>:route==='inventory'?<Inventory/>:route==='users'?<Users/>:<Shop/>;
 return <div className="app-shell"><aside className={`sidebar no-print ${nav?'open':''}`}><div className="brand"><div className="brand-symbol"><Sparkles size={26}/></div><div>DIWALI<small>CRACKERS POS</small></div><button className="mobile-close icon" aria-label="Close menu" onClick={()=>setNav(false)}><X/></button></div><div className="nav-caption">WORKSPACE</div><nav>{links.filter(l=>!l.admin||admin).map(l=><button key={l.id} className={route===l.id?'active':''} onClick={()=>navigate(l.id)}><l.icon size={19}/>{l.label}{l.id==='pos'&&<span className="nav-plus">+</span>}</button>)}</nav><div className="sidebar-bottom"><div className="season-card"><Sparkles size={18}/><span>Make every sale<br/><b>a celebration.</b></span></div><div className="profile"><span className="avatar">{user.name.charAt(0)}</span><div><strong>{user.name}</strong><small>{user.role}</small></div><button className="icon" aria-label="Sign out" onClick={logout}><LogOut size={18}/></button></div></div></aside><div className="workspace"><header className="topbar no-print"><button className="mobile-menu icon" aria-label="Open menu" onClick={()=>setNav(true)}><Menu/></button><div><span className="muted">Workspace</span><span className="breadcrumb">/</span><strong>{links.find(l=>l.id===route)?.label}</strong></div><div className="topbar-right"><span className="today">{new Date().toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',weekday:'short',day:'numeric',month:'short',year:'numeric'})}</span><span className="badge role-badge"><ShieldCheck size={14}/>{user.role}</span></div></header><main className="main-content"><ErrorBox error={error}/>{content}</main><footer className="app-footer no-print"><span>Diwali POS</span><span>Celebrate safely. Sell confidently.</span></footer></div></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><App/></QueryClientProvider></React.StrictMode>);
